#!/bin/bash

flag=true

while [[ "$flag" == "true" ]]
do
        process_cnt=`ps -ef | grep -v "grep" | grep -v "vim" | grep -v "vi" | grep systemInfo.sh | wc -l`
        if [[ "${process_cnt}" == "0" ]]
        then
                echo "`date` | Backend Pulse not running, starting it..."
                cd /home/vc46/pulse
                ./systemInfo.sh >/dev/null 2>&1 < /dev/null & 
		sleep 5 
        fi
done
